# Generated by Django 4.1.7 on 2023-03-16 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('cosmetic', 'Cosmetic'), ('mart', 'Mart'), ('groceries', 'Groceries'), ('health', 'Health'), ('fashion', 'Fashion'), ('electronic', 'Electronic'), ('mobile', 'Mobile'), ('sports', 'Sports'), ('digital', 'Digital'), ('food', 'Food'), ('others', 'Others')], default='others', max_length=10)),
                ('unit', models.CharField(choices=[('nos', 'Nos'), ('dozen', 'Dozen'), ('kgs', 'Kgs'), ('meter', 'Meter'), ('sqft', 'Sqft'), ('sqm', 'sqm')], default='nos', max_length=10)),
                ('picture', models.ImageField(default='product_default.png', upload_to='product_pic')),
                ('description', models.TextField(blank=True, null=True)),
                ('in_stock', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('bought_on', models.DateField(blank=True, null=True)),
                ('latest_price', models.FloatField()),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('purchased_quantity', models.IntegerField()),
                ('selling_price', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bought', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_set', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sold', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
